In [3]:
import pandas as pd

df = pd.DataFrame(
    {
        "series_id": ["A", "A", "A", "A", "A", "B", "B", "B", "B", "B"],
        "date": pd.to_datetime(
            [
                "2025-01-01",
                "2025-01-02",
                "2025-01-03",
                "2025-01-04",
                "2025-01-05",
                "2025-01-01",
                "2025-01-02",
                "2025-01-03",
                "2025-01-04",
                "2025-01-05",
            ]
        ),
        "observed_demand": [10, 12, 8, 14, 16, 100, 90, 110, 95, 105],
    }
)

df = df.sort_values(["series_id", "date"]).reset_index(drop=True)
df

  series_id       date  observed_demand
0         A 2025-01-01               10
1         A 2025-01-02               12
2         A 2025-01-03                8
3         A 2025-01-04               14
4         A 2025-01-05               16
5         B 2025-01-01              100
6         B 2025-01-02               90
7         B 2025-01-03              110
8         B 2025-01-04               95
9         B 2025-01-05              105

In [4]:
grouped = df.groupby("series_id", sort=False)
grouped

In [5]:
for series_name, group in grouped:
    print(f"\n===== Grupo {series_name} =====")
    display(group)

===== Grupo A =====

  series_id       date  observed_demand
0         A 2025-01-01               10
1         A 2025-01-02               12
2         A 2025-01-03                8
3         A 2025-01-04               14
4         A 2025-01-05               16

===== Grupo B =====

  series_id       date  observed_demand
5         B 2025-01-01              100
6         B 2025-01-02               90
7         B 2025-01-03              110
8         B 2025-01-04               95
9         B 2025-01-05              105

In [6]:
grouped_observed = grouped["observed_demand"]
grouped_observed

In [7]:
for series_name, values in grouped_observed:
    print(f"\n===== observed_demand de la serie {series_name} =====")
    print(values)

===== observed_demand de la serie A =====
0    10
1    12
2     8
3    14
4    16
Name: observed_demand, dtype: int64

===== observed_demand de la serie B =====
5    100
6     90
7    110
8     95
9    105
Name: observed_demand, dtype: int64

In [8]:
shifted_1 = grouped["observed_demand"].shift(1)
shifted_1

0      NaN
1     10.0
2     12.0
3      8.0
4     14.0
5      NaN
6    100.0
7     90.0
8    110.0
9     95.0
Name: observed_demand, dtype: float64

In [9]:
df["demand_lag_1"] = grouped["observed_demand"].shift(1)
df

  series_id       date  observed_demand  demand_lag_1
0         A 2025-01-01               10           NaN
1         A 2025-01-02               12          10.0
2         A 2025-01-03                8          12.0
3         A 2025-01-04               14           8.0
4         A 2025-01-05               16          14.0
5         B 2025-01-01              100           NaN
6         B 2025-01-02               90         100.0
7         B 2025-01-03              110          90.0
8         B 2025-01-04               95         110.0
9         B 2025-01-05              105          95.0

In [10]:
df["bad_shift_without_groupby"] = df["observed_demand"].shift(1)
df

,series_id,date,observed_demand,demand_lag_1,bad_shift_without_groupby
0,A,2025-01-01,10,NaN,NaN
1,A,2025-01-02,12,10.0,10.0
2,A,2025-01-03,8,12.0,12.0
3,A,2025-01-04,14,8.0,8.0
4,A,2025-01-05,16,14.0,14.0
5,B,2025-01-01,100,NaN,16.0
6,B,2025-01-02,90,100.0,100.0
7,B,2025-01-03,110,90.0,90.0
8,B,2025-01-04,95,110.0,110.0
9,B,2025-01-05,105,95.0,95.0

In [11]:
df["roll_mean_3"] = grouped["observed_demand"].transform(
    lambda series: series.shift(1).rolling(window=3, min_periods=3).mean()
)

df

,series_id,date,observed_demand,demand_lag_1,bad_shift_without_groupby,roll_mean_3
0,A,2025-01-01,10,NaN,NaN,NaN
1,A,2025-01-02,12,10.0,10.0,NaN
2,A,2025-01-03,8,12.0,12.0,NaN
3,A,2025-01-04,14,8.0,8.0,10.000000
4,A,2025-01-05,16,14.0,14.0,11.333333
5,B,2025-01-01,100,NaN,16.0,NaN
6,B,2025-01-02,90,100.0,100.0,NaN
7,B,2025-01-03,110,90.0,90.0,NaN
8,B,2025-01-04,95,110.0,110.0,100.000000
9,B,2025-01-05,105,95.0,95.0,98.333333

In [12]:
df["roll_sum_3"] = grouped["observed_demand"].transform(
    lambda series: series.shift(1).rolling(window=3, min_periods=3).sum()
)

df["roll_std_3"] = grouped["observed_demand"].transform(
    lambda series: series.shift(1).rolling(window=3, min_periods=3).std()
)

df

,series_id,date,observed_demand,demand_lag_1,bad_shift_without_groupby,roll_mean_3,roll_sum_3,roll_std_3
0,A,2025-01-01,10,NaN,NaN,NaN,NaN,NaN
1,A,2025-01-02,12,10.0,10.0,NaN,NaN,NaN
2,A,2025-01-03,8,12.0,12.0,NaN,NaN,NaN
3,A,2025-01-04,14,8.0,8.0,10.000000,30.0,2.00000
4,A,2025-01-05,16,14.0,14.0,11.333333,34.0,3.05505
5,B,2025-01-01,100,NaN,16.0,NaN,NaN,NaN
6,B,2025-01-02,90,100.0,100.0,NaN,NaN,NaN
7,B,2025-01-03,110,90.0,90.0,NaN,NaN,NaN
8,B,2025-01-04,95,110.0,110.0,100.000000,300.0,10.00000
9,B,2025-01-05,105,95.0,95.0,98.333333,295.0,10.40833

In [13]:
for series_name, group in df.groupby("series_id", sort=False):
    print(f"\n===== Serie {series_name} =====")
    display(
        group[
            [
                "series_id",
                "date",
                "observed_demand",
                "demand_lag_1",
                "roll_mean_3",
                "roll_sum_3",
                "roll_std_3",
            ]
        ]
    )

===== Serie A =====

,series_id,date,observed_demand,demand_lag_1,roll_mean_3,roll_sum_3,roll_std_3
0,A,2025-01-01,10,NaN,NaN,NaN,NaN
1,A,2025-01-02,12,10.0,NaN,NaN,NaN
2,A,2025-01-03,8,12.0,NaN,NaN,NaN
3,A,2025-01-04,14,8.0,10.000000,30.0,2.00000
4,A,2025-01-05,16,14.0,11.333333,34.0,3.05505

===== Serie B =====

,series_id,date,observed_demand,demand_lag_1,roll_mean_3,roll_sum_3,roll_std_3
5,B,2025-01-01,100,NaN,NaN,NaN,NaN
6,B,2025-01-02,90,100.0,NaN,NaN,NaN
7,B,2025-01-03,110,90.0,NaN,NaN,NaN
8,B,2025-01-04,95,110.0,100.000000,300.0,10.00000
9,B,2025-01-05,105,95.0,98.333333,295.0,10.40833

In [14]:
serie_a = df[df["series_id"] == "A"].copy()

serie_a["shift_1"] = serie_a["observed_demand"].shift(1)
serie_a["manual_roll_mean_3"] = (
    serie_a["shift_1"].rolling(window=3, min_periods=3).mean()
)
serie_a["manual_roll_sum_3"] = serie_a["shift_1"].rolling(window=3, min_periods=3).sum()
serie_a["manual_roll_std_3"] = serie_a["shift_1"].rolling(window=3, min_periods=3).std()

serie_a

,series_id,date,observed_demand,demand_lag_1,bad_shift_without_groupby,roll_mean_3,roll_sum_3,roll_std_3,shift_1,manual_roll_mean_3,manual_roll_sum_3,manual_roll_std_3
0,A,2025-01-01,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,A,2025-01-02,12,10.0,10.0,NaN,NaN,NaN,10.0,NaN,NaN,NaN
2,A,2025-01-03,8,12.0,12.0,NaN,NaN,NaN,12.0,NaN,NaN,NaN
3,A,2025-01-04,14,8.0,8.0,10.000000,30.0,2.00000,8.0,10.000000,30.0,2.00000
4,A,2025-01-05,16,14.0,14.0,11.333333,34.0,3.05505,14.0,11.333333,34.0,3.05505